#theme: jekyll-theme-minimal
# remote_theme: allejo/jekyll-docs-theme@v1.0.0
theme: jekyll-docs-theme

# name of the software
name: Spaartechnologie

links:
  header:
    - title: Bewijs van Werk
      icon: home
      brand: true
      url: https://bewijsvanwerk.com/
  homepage:
    - title: Bewijs van Werk
      icon: github
      brand: true
      url: https://bewijsvanwerk.com/
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/SovereignNode/Spaartechnologie
    - title: Contact
      icon: bug
      url: https://twitter.com/sovereignhodler

ui:
  mode: 'auto' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#a20000"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#b64005"
      color2: "#f7931a"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

social:
  twitter:
    enabled: true
    via:
    hash:
    account:
  facebook:
    enabled: true
    profileUrl:
