#theme: jekyll-theme-minimal
remote_theme: allejo/jekyll-docs-theme@v1.0.0


search_enabled: true
aux_links:
    "Terug naar Bewijs van Werk":
      - "https://bewijsvanwerk.com"
    "Help mee! Draag bij op Github":
      - "https://github.com/SovereignNode/bitcoin-intro/"
# Set a path/url to a logo that will be displayed instead of the title
