#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
    "Contribute! Source on GitHub":
      - "https://github.com/SovereignNode/bitcoin-intro/"
# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/banner.jpg"
